export const chats = [
  {
    id: 'alex-design',
    name: 'Alex Morgan',
    avatar: 'AM',
    type: 'direct',
    time: '2m',
    unread: 2,
    lastMessage: 'I shared the new onboarding screens for review.',
    role: 'Product Designer',
    about: 'Focuses on polished UI systems, motion details, and consistent component behavior.',
    statusColor: 'bg-emerald-400',
  },
  {
    id: 'launch-squad',
    name: 'Launch Squad',
    avatar: 'LS',
    type: 'group',
    time: '12m',
    unread: 6,
    lastMessage: 'Standup moved to 4:30 PM. Please drop blockers here.',
    role: 'Cross-functional Group',
    about: 'Planning space for product, design, and engineering as features move toward release.',
    statusColor: 'bg-cyan-300',
  },
  {
    id: 'mira-support',
    name: 'Mira Patel',
    avatar: 'MP',
    type: 'direct',
    time: '35m',
    unread: 0,
    lastMessage: 'Can you help review the latest support flow copy?',
    role: 'Customer Success Lead',
    about: 'Keeps customer-facing comms clear, calm, and fast across support operations.',
    statusColor: 'bg-amber-300',
  },
  {
    id: 'dev-circle',
    name: 'Dev Circle',
    avatar: 'DC',
    type: 'group',
    time: '1h',
    unread: 3,
    lastMessage: 'Backend API is ready for the next round of chat integration.',
    role: 'Engineering Group',
    about: 'Shared engineering room for feature updates, blockers, and release coordination.',
    statusColor: 'bg-violet-300',
  },
];
